# Generated by Django 5.0.7 on 2024-08-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('incomplete', 'Incomplete'), ('blocked', 'Blocked'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded'), ('expired', 'Expired'), ('disputed', 'Disputed'), ('early_fraud_warning', 'Early Fraud Warning'), ('partially_paid', 'Partially Paid'), ('partially_refunded', 'Partially Refunded'), ('pending', 'Pending'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('uncaptured', 'Uncaptured'), ('waiting_on_funding', 'Waiting on Funding')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'CASH'), ('stripe', 'stripe')], default='stripe', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
