# Generated by Django 5.0.7 on 2024-08-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_product_options_alter_order_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_uz', 'name_ru', 'name_en'], 'verbose_name': 'Product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'CASH'), ('stripe', 'stripe')], default='stripe', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'),
        ),
    ]
