# Generated by Django 5.0.7 on 2024-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_product_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_uz', 'name_ru', 'name_en'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('incomplete', 'Incomplete'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded'), ('expired', 'Expired'), ('pending', 'Pending')], max_length=20),
        ),
    ]
