# Generated by Django 5.0.7 on 2024-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_uz', 'name_ru', 'name_en'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Order Histories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('incomplete', 'Incomplete'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('cash', 'Cash'), ('stripe', 'Stripe')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
