# Generated by Django 5.0.6 on 2024-07-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_en',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='comment_en',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='latitude_en',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='latitude_ru',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment_uz',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude_uz',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_uz',
        ),
    ]
